var annotated =
[
    [ "CMSGHDR", "group__bsd__structs.html#struct_c_m_s_g_h_d_r", "group__bsd__structs_struct_c_m_s_g_h_d_r" ],
    [ "DRIVER_MODEM", "group__net_d_s___modem.html#struct_d_r_i_v_e_r___m_o_d_e_m", "group__net_d_s___modem_struct_d_r_i_v_e_r___m_o_d_e_m" ],
    [ "evr_access", "net__evr_8h.html#unionevr__access", "net__evr_8h_unionevr__access" ],
    [ "EVR_ADDR", "net__evr_8h.html#struct_e_v_r___a_d_d_r", "net__evr_8h_struct_e_v_r___a_d_d_r" ],
    [ "fd_set", "group__bsd__structs.html#structfd__set", "group__bsd__structs_structfd__set" ],
    [ "HOSTENT", "group__bsd__structs.html#struct_h_o_s_t_e_n_t", "group__bsd__structs_struct_h_o_s_t_e_n_t" ],
    [ "IN6_ADDR", "group__bsd__structs.html#struct_i_n6___a_d_d_r", null ],
    [ "IN6_ADDR.__unnamed__", "group__bsd__structs.html#union_i_n6___a_d_d_r_8____unnamed____", "group__bsd__structs_union_i_n6___a_d_d_r_8____unnamed____" ],
    [ "IN_ADDR", "group__bsd__structs.html#struct_i_n___a_d_d_r", null ],
    [ "IN_ADDR.__unnamed__", "group__bsd__structs.html#union_i_n___a_d_d_r_8____unnamed____", "group__bsd__structs_union_i_n___a_d_d_r_8____unnamed____" ],
    [ "IN_ADDR.__unnamed__.__unnamed__", "group__bsd__structs.html#struct_i_n___a_d_d_r_8____unnamed_____8____unnamed____", "group__bsd__structs_struct_i_n___a_d_d_r_8____unnamed_____8____unnamed____" ],
    [ "IN_ADDR.__unnamed__.__unnamed__", "group__bsd__structs.html#struct_i_n___a_d_d_r_8____unnamed_____8____unnamed____", "group__bsd__structs_struct_i_n___a_d_d_r_8____unnamed_____8____unnamed____" ],
    [ "IOVEC", "group__bsd__structs.html#struct_i_o_v_e_c", "group__bsd__structs_struct_i_o_v_e_c" ],
    [ "MSGHDR", "group__bsd__structs.html#struct_m_s_g_h_d_r", "group__bsd__structs_struct_m_s_g_h_d_r" ],
    [ "NET_ADDR", "group__network__structs.html#struct_n_e_t___a_d_d_r", "group__network__structs_struct_n_e_t___a_d_d_r" ],
    [ "NET_ADDR4", "group__network__structs.html#struct_n_e_t___a_d_d_r4", "group__network__structs_struct_n_e_t___a_d_d_r4" ],
    [ "NET_DHCP_OPTION_ITEM", "group___common__structs.html#struct_n_e_t___d_h_c_p___o_p_t_i_o_n___i_t_e_m", "group___common__structs_struct_n_e_t___d_h_c_p___o_p_t_i_o_n___i_t_e_m" ],
    [ "NET_ETH_LINK_INFO", "group___ethernet__structs.html#struct_n_e_t___e_t_h___l_i_n_k___i_n_f_o", "group___ethernet__structs_struct_n_e_t___e_t_h___l_i_n_k___i_n_f_o" ],
    [ "NET_FS_TIME", "rl__net__ds_8h.html#struct_n_e_t___f_s___t_i_m_e", "rl__net__ds_8h_struct_n_e_t___f_s___t_i_m_e" ],
    [ "NET_SMTP_MAIL", "group__smtp__structs.html#struct_n_e_t___s_m_t_p___m_a_i_l", "group__smtp__structs_struct_n_e_t___s_m_t_p___m_a_i_l" ],
    [ "NET_SMTP_MTA", "group__smtp__structs.html#struct_n_e_t___s_m_t_p___m_t_a", "group__smtp__structs_struct_n_e_t___s_m_t_p___m_t_a" ],
    [ "NET_SNMP_MIB_INFO", "group__snmp__structs.html#struct_n_e_t___s_n_m_p___m_i_b___i_n_f_o", "group__snmp__structs_struct_n_e_t___s_n_m_p___m_i_b___i_n_f_o" ],
    [ "NET_WIFI_CONFIG", "group___wifi__structs.html#struct_n_e_t___w_i_f_i___c_o_n_f_i_g", "group___wifi__structs_struct_n_e_t___w_i_f_i___c_o_n_f_i_g" ],
    [ "NET_WIFI_NET_INFO", "group___wifi__structs.html#struct_n_e_t___w_i_f_i___n_e_t___i_n_f_o", "group___wifi__structs_struct_n_e_t___w_i_f_i___n_e_t___i_n_f_o" ],
    [ "NET_WIFI_SCAN_INFO", "group___wifi__structs.html#struct_n_e_t___w_i_f_i___s_c_a_n___i_n_f_o", "group___wifi__structs_struct_n_e_t___w_i_f_i___s_c_a_n___i_n_f_o" ],
    [ "SOCKADDR", "group__bsd__structs.html#struct_s_o_c_k_a_d_d_r", "group__bsd__structs_struct_s_o_c_k_a_d_d_r" ],
    [ "SOCKADDR_IN", "group__bsd__structs.html#struct_s_o_c_k_a_d_d_r___i_n", "group__bsd__structs_struct_s_o_c_k_a_d_d_r___i_n" ],
    [ "SOCKADDR_IN6", "group__bsd__structs.html#struct_s_o_c_k_a_d_d_r___i_n6", "group__bsd__structs_struct_s_o_c_k_a_d_d_r___i_n6" ],
    [ "SOCKADDR_STORAGE", "rl__net__ds_8h.html#struct_s_o_c_k_a_d_d_r___s_t_o_r_a_g_e", "rl__net__ds_8h_struct_s_o_c_k_a_d_d_r___s_t_o_r_a_g_e" ],
    [ "timeval", "group__bsd__structs.html#structtimeval", "group__bsd__structs_structtimeval" ]
];