var searchData=
[
  ['cdc_3a_20communication_20device_20class',['CDC: Communication Device Class',['../_c_d_c.html',1,'USB_Classes']]],
  ['cdc_5fline_5fcoding',['CDC_LINE_CODING',['../group__usbd__structs.html#struct_c_d_c___l_i_n_e___c_o_d_i_n_g',1,'']]],
  ['custom_20class',['Custom Class',['../_custom_class.html',1,'USB_Classes']]],
  ['custom_20usb_20device_20_28winusb_5fecho_29',['Custom USB Device (WinUSB_Echo)',['../dev_cc_tutorial.html',1,'USB_Device_Tutorial']]],
  ['configuration_20descriptor',['Configuration Descriptor',['../_u_s_b__configuration__descriptor.html',1,'USB_Descriptors']]],
  ['control_20transfers',['Control Transfers',['../_u_s_b__control__transfers.html',1,'USB_Endpoints']]],
  ['configuration',['Configuration',['../group__usbd__adc_functions__conf.html',1,'']]],
  ['cdc_3a_20communication_20device_20class_20_28acm_29',['CDC: Communication Device Class (ACM)',['../group__usbd__cdc_functions__acm.html',1,'']]],
  ['configuration',['Configuration',['../group__usbd__cdc_functions__acm__conf.html',1,'']]],
  ['cdc_3a_20communication_20device_20class_20_28ncm_29',['CDC: Communication Device Class (NCM)',['../group__usbd__cdc_functions__ncm.html',1,'']]],
  ['configuration',['Configuration',['../group__usbd__cdc_functions__ncm__conf.html',1,'']]],
  ['custom_20class',['Custom Class',['../group__usbd__class_functions.html',1,'']]],
  ['configuration',['Configuration',['../group__usbd__class_functions__conf.html',1,'']]],
  ['core',['Core',['../group__usbd__core_functions.html',1,'']]],
  ['configuration',['Configuration',['../group__usbd__core_functions__conf.html',1,'']]],
  ['configuration',['Configuration',['../group__usbd__hid_functions__conf.html',1,'']]],
  ['configuration',['Configuration',['../group__usbd__msc_functions__conf.html',1,'']]],
  ['cdc_20_28acm_29_3a_20communication_20device_20class_20_28abstract_20control_20model_29',['CDC (ACM): Communication Device Class (Abstract Control Model)',['../group__usbh__cdcacm_functions.html',1,'']]],
  ['configuration',['Configuration',['../group__usbh__cdcacm_functions__conf.html',1,'']]],
  ['core',['Core',['../group__usbh__core_functions.html',1,'']]],
  ['configuration',['Configuration',['../group__usbh__core_functions__conf.html',1,'']]],
  ['custom_20class',['Custom Class',['../group__usbh__custom_functions.html',1,'']]],
  ['configuration',['Configuration',['../group__usbh__custom_functions__conf.html',1,'']]],
  ['configuration',['Configuration',['../group__usbh__hid_functions__conf.html',1,'']]],
  ['configuration',['Configuration',['../group__usbh__msc_functions__conf.html',1,'']]]
];
